name = "hoh-website"
compatibility_date = "2024-12-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
pages_build_command = "pnpm install --no-frozen-lockfile && pnpm build"